# @generated by usage-cli from .usage.kdl
_browser_tab() {
    if ! type -p usage &> /dev/null; then
        echo >&2
        echo "Error: usage CLI not found. This is required for completions to work in browser-tab." >&2
        echo "See https://usage.jdx.dev for more information." >&2
        return 1
    fi

	local cur prev words cword was_split comp_args
    _comp_initialize -n : -- "$@" || return
    local spec_file="${TMPDIR:-/tmp}/usage__usage_spec_browser_tab.spec"
    cat >| "$spec_file" <<'__USAGE_EOF__'
name browser-tab
bin browser-tab
about "browser-tab — MCP server + CLI + TUI (single bin, subcommand dispatch)"
flag --json help="Emit machine-readable JSON output"
flag "-q --quiet" help="Suppress non-error output"
flag "-v --verbose" help="Log debug-level info to stderr"
flag --no-color help="Disable colors"
cmd mcp help="Run the MCP server (stdio)"
cmd tui help="Launch the Ink TUI"
cmd doctor help="Run preflight checks (Node version, native module, config dir)"
cmd repl help="Interactive REPL driving the in-process dispatcher" {
    alias console
}
cmd health help="Print server health snapshot (calls health_check in-process)"
cmd list help="List open browser windows and tabs (Chrome/Brave/Chromium/Safari)" {
    flag --browser help="Restrict to one browser: chrome|chromium|brave|safari" {
        arg <name>
    }
    flag --window help="Restrict to one window (opaque windowId)" {
        arg <id>
    }
    flag --url help="Filter tabs by URL substring" {
        arg <substring>
    }
    flag --fields help="Field set: core (trimmed) or full (default)" {
        arg <set>
    }
}
cmd journal help="Show recorded focus/navigation history" {
    flag --view help="windowMru | tabMru | journey | recent" {
        arg <view>
    }
    flag --browser help="Restrict to one browser" {
        arg <name>
    }
    flag --window help="Window handle (required for tabMru)" {
        arg <id>
    }
    flag --tab help="Tab handle (required for journey)" {
        arg <id>
    }
    flag --limit help="Max records" {
        arg <n>
    }
}
cmd page help="Extract a tab's content or live state (needs daemon + extension)" {
    flag --mode help="text | metadata | state" {
        arg <mode>
    }
    flag --force help="Bypass the navEpoch cache and re-extract"
    arg <tabId>
}
cmd annotate help="Read or write a URL-keyed note in the daemon annotation store" {
    flag --note help="Note to store (omit to read the existing note)" {
        arg <text>
    }
    arg <url>
}
cmd focus help="Focus a tab and raise its window" {
    arg <tabId>
}
cmd close help="Close a tab" {
    arg <tabId>
}
cmd open help="Open an http(s) URL in a new tab" {
    flag --browser help=chrome|chromium|brave|safari {
        arg <name>
    }
    flag --window help="Open in a specific window (opaque windowId)" {
        arg <id>
    }
    flag --no-activate help="Open in the background"
    arg <url>
}
cmd move help="Move a tab to another window (true moves need daemon + extension)" {
    flag --target-window help="Destination windowId" {
        arg <id>
    }
    flag --index help="0-based destination position" {
        arg <n>
    }
    flag --new-window help="Move into a newly created window"
    flag --allow-reload help="Safari: accept the reload-based AppleScript move"
    arg <tabId>
}
cmd act help="Run an action on a tab (mute|unmute|pin|unpin|discard|reload|navigate|back|forward|duplicate)" {
    flag --url help="Destination URL (required for navigate)" {
        arg <url>
    }
    arg <tabId>
    arg <action>
}
cmd group help="Manage Chrome tab groups (create|add|remove|update|move)" {
    flag --tabs help="Comma-separated tab handles (create/add/remove)" {
        arg <ids>
    }
    flag --group help="Group handle (add/remove/update/move)" {
        arg <id>
    }
    flag --browser help=chrome|chromium|brave {
        arg <name>
    }
    flag --title help="Group title (create/update)" {
        arg <title>
    }
    flag --color help="Group color (create/update)" {
        arg <color>
    }
    flag --collapsed help="Collapse the group (update)"
    flag --target-window help="Destination window (move)" {
        arg <id>
    }
    flag --index help="0-based destination position (move)" {
        arg <n>
    }
    arg <action>
}
cmd window help="Window operations: open | set | close" {
    cmd open help="Open a new window with one or more URLs" {
        flag --browser help=chrome|chromium|brave|safari {
            arg <name>
        }
        flag --bounds help="Global-coordinate frame x,y,w,h" {
            arg <bounds>
        }
        flag --display help="0-based display index (fills that monitor)" {
            arg <n>
        }
        flag --state help=normal|minimized|maximized|fullscreen {
            arg <state>
        }
        flag --incognito help="Open a private/incognito window"
        flag --no-focus help="Open in the background"
        arg <url>… var=#true
    }
    cmd set help="Move/resize/minimize/foreground a window" {
        flag --bounds help="Global-coordinate frame x,y,w,h" {
            arg <bounds>
        }
        flag --display help="0-based display index (fills that monitor)" {
            arg <n>
        }
        flag --state help=normal|minimized|maximized|fullscreen {
            arg <state>
        }
        flag --focus help="Raise/foreground the window"
        arg <windowId>
    }
    cmd close help="Close an entire window and all its tabs" {
        arg <windowId>
    }
}
cmd daemon help="Manage the browser-tab daemon" {
    cmd run help="Run the daemon in the foreground (launchd invokes this)"
    cmd install help="Install + start the launchd LaunchAgent"
    cmd uninstall help="Stop + remove the launchd LaunchAgent"
    cmd status help="Show launchd + live daemon status"
    cmd token help="Print the extension auth token"
    cmd stop help="Stop the daemon (launchctl bootout)"
    cmd restart help="Restart the daemon (launchctl kickstart -k)"
}
cmd noop help="Demo: call the noop tool" {
    flag --input help="Input string to echo" required=#true {
        arg <text>
    }
    flag --upper help="Return upper-cased"
}
__USAGE_EOF__
    # shellcheck disable=SC2207
	_comp_compgen -- -W "$(command usage complete-word --shell bash -f "$spec_file" --cword="$cword" -- "${words[@]}")"
	_comp_ltrim_colon_completions "$cur"
    # shellcheck disable=SC2181
    if [[ $? -ne 0 ]]; then
        unset COMPREPLY
    fi
    return 0
}

if [[ "${BASH_VERSINFO[0]}" -eq 4 && "${BASH_VERSINFO[1]}" -ge 4 || "${BASH_VERSINFO[0]}" -gt 4 ]]; then
    shopt -u hostcomplete && complete -o nospace -o bashdefault -o nosort -F _browser_tab browser-tab
else
    shopt -u hostcomplete && complete -o nospace -o bashdefault -F _browser_tab browser-tab
fi
# vim: noet ci pi sts=0 sw=4 ts=4 ft=sh
