# @generated by usage-cli from .usage.kdl

# if "usage" is not installed show an error
if ! type -p usage &> /dev/null
    echo >&2
    echo "Error: usage CLI not found. This is required for completions to work in browser-tab." >&2
    echo "See https://usage.jdx.dev for more information." >&2
    return 1
end

set _usage_spec_browser_tab 'name browser-tab
bin browser-tab
about "browser-tab — MCP server + CLI + TUI (single bin, subcommand dispatch)"
flag --json help="Emit machine-readable JSON output"
flag "-q --quiet" help="Suppress non-error output"
flag "-v --verbose" help="Log debug-level info to stderr"
flag --no-color help="Disable colors"
cmd mcp help="Run the MCP server (stdio)"
cmd tui help="Launch the Ink TUI"
cmd doctor help="Run preflight checks (Node version, native module, config dir)"
cmd repl help="Interactive REPL driving the in-process dispatcher" {
    alias console
}
cmd health help="Print server health snapshot (calls health_check in-process)"
cmd list help="List open browser windows and tabs (Chrome/Brave/Chromium/Safari)" {
    flag --browser help="Restrict to one browser: chrome|chromium|brave|safari" {
        arg <name>
    }
    flag --window help="Restrict to one window (opaque windowId)" {
        arg <id>
    }
    flag --url help="Filter tabs by URL substring" {
        arg <substring>
    }
    flag --fields help="Field set: core (trimmed) or full (default)" {
        arg <set>
    }
}
cmd journal help="Show recorded focus/navigation history" {
    flag --view help="windowMru | tabMru | journey | recent" {
        arg <view>
    }
    flag --browser help="Restrict to one browser" {
        arg <name>
    }
    flag --window help="Window handle (required for tabMru)" {
        arg <id>
    }
    flag --tab help="Tab handle (required for journey)" {
        arg <id>
    }
    flag --limit help="Max records" {
        arg <n>
    }
}
cmd focus help="Focus a tab and raise its window" {
    arg <tabId>
}
cmd close help="Close a tab" {
    arg <tabId>
}
cmd open help="Open an http(s) URL in a new tab" {
    flag --browser help=chrome|chromium|brave|safari {
        arg <name>
    }
    flag --window help="Open in a specific window (opaque windowId)" {
        arg <id>
    }
    flag --no-activate help="Open in the background"
    arg <url>
}
cmd move help="Move a tab to another window (true moves need daemon + extension)" {
    flag --target-window help="Destination windowId" {
        arg <id>
    }
    flag --index help="0-based destination position" {
        arg <n>
    }
    flag --new-window help="Move into a newly created window"
    flag --allow-reload help="Safari: accept the reload-based AppleScript move"
    arg <tabId>
}
cmd daemon help="Manage the browser-tab daemon" {
    cmd run help="Run the daemon in the foreground (launchd invokes this)"
    cmd install help="Install + start the launchd LaunchAgent"
    cmd uninstall help="Stop + remove the launchd LaunchAgent"
    cmd status help="Show launchd + live daemon status"
    cmd token help="Print the extension auth token"
    cmd stop help="Stop the daemon (launchctl bootout)"
    cmd restart help="Restart the daemon (launchctl kickstart -k)"
}
cmd noop help="Demo: call the noop tool" {
    flag --input help="Input string to echo" required=#true {
        arg <text>
    }
    flag --upper help="Return upper-cased"
}
'
set -l tmpdir (if set -q TMPDIR; echo $TMPDIR; else; echo /tmp; end)
set -l spec_file "$tmpdir/usage__usage_spec_browser_tab.spec"
echo $_usage_spec_browser_tab > "$spec_file"

set -l tokens
if commandline -x >/dev/null 2>&1
    complete -xc browser-tab -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -xpc) (commandline -t))"
else
    complete -xc browser-tab -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -opc) (commandline -t))"
end
