/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * One on-screen CoreGraphics window. windowId is the CGWindowID — the
 * same id namespace yabai reports, which makes it the join key between
 * browser windows and the window manager. No titles are read (that would
 * require the Screen Recording TCC permission).
 */
export interface CgWindowInfo {
  windowId: number
  ownerPid: number
  x: number
  y: number
  w: number
  h: number
  layer: number
}

/**
 * One active display. x/y are the display's global-screen origin (points,
 * top-left), so `display` targets in open_window/set_window translate into
 * global bounds. No TCC permission required (CGDisplayBounds is public).
 */
export interface DisplayInfo {
  displayId: number
  x: number
  y: number
  w: number
  h: number
  isMain: boolean
}

/** Plain hello-world for integration tests. */
export declare function hello(name: string): string

/**
 * Enumerate on-screen CoreGraphics windows: CGWindowID, owner pid,
 * bounds, layer. CGWindowIDs are the same namespace yabai window ids
 * live in, so this is the correlation source for `cgWindowId`.
 *
 * Deliberately does NOT read kCGWindowName — window titles require the
 * Screen Recording TCC permission; ids/pids/bounds do not.
 */
export declare function listCgWindows(): Array<CgWindowInfo>

/**
 * Enumerate active displays with their global-screen bounds. Feeds the
 * `display` targeting in open_window/set_window (index into this array)
 * so window placement can be expressed per-monitor. Empty when the native
 * module is unavailable — the TS side then errors on display targeting
 * and still honors explicit absolute bounds.
 */
export declare function listDisplays(): Array<DisplayInfo>

/**
 * Demo Rust path for the `noop` MCP tool. Echoes the input string,
 * optionally upper-cased, and reports the wall-clock duration in
 * microseconds.
 */
export declare function noopAccel(input: NoopInput): NoopOutput

export interface NoopInput {
  input: string
  upper: boolean
}

export interface NoopOutput {
  echo: string
  /** Either "ts" or "rust"; the Rust path always returns "rust". */
  engine: string
  durationMicros: number
}
